version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Job Details" present in index.html file"
            - grep "Job Details" index.html
            
            - echo "Post-build phase"
            - |
              # Deployment Script
              # Clone the GitHub repository, build, and deploy
        
              # Clone the repository to a temporary directory
              git clone -b master https://github.com/armaanroohi/code_deploy_demo-main.git /tmp/deployment
        
              # Optionally, build your project (if needed)
              # Example for npm-based project:
              # cd /tmp/deployment
              # npm install
              # npm run build
        
              # Copy the built files to the web server directory
              sudo rsync -av /tmp/deployment/ /var/www/html/
        
              # Clean up the temporary directory
              rm -rf /tmp/deployment
        
              # Restart the web server (if necessary)
              # Example for Apache:
              # sudo service apache2 restart
    post_build:
        commands:
            - echo "Post-build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - index.html
        - appspec.yml  
    discard-paths: yes

            
