version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Job Details" present in index.html file"
            - grep "Job Details" index.html
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - index.html
        - appspec.yml
        - css/
        - images/
        - fonts/
        - js/
        
        
    discard-paths: yes

            
